name: coronavirus_no_brasil
description: A coronavirus tracker in Brazil.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # Mobx (flutter packages pub run build_runner watch --delete-conflicting-outputs)
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  # Service locator
  get_it: ^3.1.0
  # UI
  flutter_svg: ^0.17.3+1
  convex_bottom_bar: ^2.1.1
  simple_animations: ^1.3.3
  url_launcher: ^5.4.2
  cupertino_icons: ^0.1.2
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  dio: ^3.0.9
  http: ^0.12.0+3
  data_connection_checker: ^0.3.4
  # Local cache
  hive: ^1.4.1+1
  csv: ^4.0.3
  # Charts
  charts_common: ^0.9.0
  charts_flutter: ^0.9.0
  hexcolor: ^1.0.1
  # For OS-specific directory paths
  path_provider: ^1.3.0
  # Formatting
  diacritic: ^0.1.1
  intl: ^0.16.1 
  # Markdown
  flutter_markdown: ^0.3.4

dev_dependencies:
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: ^0.0.1

  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "Coronavírus no Brasil"

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  fonts:
    - family: LibreBaskerville-Regular
      fonts:
        - asset: fonts/LibreBaskerville-Regular.otf
